[window]
opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "UbuntuMono Nerd Font"
bold.family = "UbuntuMono Nerd Font"
italic.family = "UbuntuMono Nerd Font"
bold_italic.family = "UbuntuMono Nerd Font"

size = 18.0
